// examples/angular/src/app/LocalHostWarning/localHostWarning.component.ts
import { Component } from '@angular/core';

@Component({
  templateUrl: './localHostWarning.component.html',
})
export class LocalHostWarning {}

<div>
  <p>
    Contentful Apps need to run inside the Contentful web app to function properly. Install the app
    into a space and render your app into one of the
    <a
      href="https://www.contentful.com/developers/docs/extensibility/ui-extensions/sdk-reference/#locations">
      available locations
    </a>
    .
  </p>
  <p>
    Follow
    <a
      href="https://www.contentful.com/developers/docs/extensibility/app-framework/tutorial/#embed-your-app-in-the-contentful-web-app">
      our guide
    </a>
    to get started or
    <a href="https://app.contentful.com/deeplink?link=apps">open Contentful</a>
    to manage your app.
  </p>
</div>

// examples/vue/src/components/LocalhostWarning.vue
<template>
  <p>
    Contentful Apps need to run inside the Contentful web app to function properly. Install the app
    into a space and render your app into one of the
    <a
      href="https://www.contentful.com/developers/docs/extensibility/ui-extensions/sdk-reference/#locations">
      available locations
    </a>
    .
  </p>
  <p>
    Follow
    <a
      href="https://www.contentful.com/developers/docs/extensibility/app-framework/tutorial/#embed-your-app-in-the-contentful-web-app">
      our guide
    </a>
    to get started or
    <a href="https://app.contentful.com/deeplink?link=apps">open Contentful</a>
    to manage your app.
  </p>
</template>
