// examples/vue/src/App.vue
<template>
    <template v-if="isConfigScreen()">
        <AppConfigLocation :sdk="sdk" />

    </template>
    <template v-if="isField()">
        <FieldLocation :sdk="sdk" />
    </template>
</template>
  
<script setup lang="ts">
import { locations, type ConfigAppSDK, type FieldAppSDK } from '@contentful/app-sdk';
import { onMounted, reactive } from 'vue';
import { inject } from 'vue'
import AppConfigLocation from './locations/AppConfigLocation.vue';
import FieldLocation from './locations/FieldLocation.vue';

const $sdk: ConfigAppSDK | FieldAppSDK = inject('$sdk')!;
const sdk = reactive($sdk)

const isConfigScreen = () => {
    return sdk.location.is(locations.LOCATION_APP_CONFIG)
}

const isField = () => {
    return sdk.location.is(locations.LOCATION_ENTRY_FIELD)
}


</script>

// apps/color-picker/src/App.tsx
import React, { useMemo } from 'react';
import { locations } from '@contentful/app-sdk';
import ConfigScreen from './locations/ConfigScreen';
import Field from './locations/Field';
import { useSDK } from '@contentful/react-apps-toolkit';

const ComponentLocationSettings = {
  [locations.LOCATION_APP_CONFIG]: ConfigScreen,
  [locations.LOCATION_ENTRY_FIELD]: Field,
};

const App = () => {
  const sdk = useSDK();

  const Component = useMemo(() => {
    for (const [location, component] of Object.entries(
      ComponentLocationSettings,
    )) {
      if (sdk.location.is(location)) {
        return component;
      }
    }
  }, [sdk.location]);

  return Component ? <Component /> : null;
};

export default App;
